version: '3.8'

services:
  warehouse-zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    platform: linux/amd64
    container_name: warehouse_zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  warehouse-kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: warehouse_kafka
    depends_on:
      - warehouse-zookeeper
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: warehouse-zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://warehouse-kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  warehouse-kafdrop:
    image: obsidiandynamics/kafdrop
    platform: linux/amd64
    container_name: warehouse_kafdrop
    depends_on:
      - warehouse-kafka
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKER_CONNECT: warehouse-kafka:9092
